---
galaxy_info:
  role_name: checkmk
  namespace: graylock
  author: Sidney
  description: Comprehensive CheckMK monitoring deployment with server and agent support
  company: Graylock Homelab
  license: MIT
  min_ansible_version: "2.14"

  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
        - noble
    - name: Debian
      versions:
        - bullseye
        - bookworm
    - name: EL
      versions:
        - "8"
        - "9"

  galaxy_tags:
    - monitoring
    - checkmk
    - nagios
    - docker
    - metrics
    - observability
    - alerting
    - infrastructure
    - performance

dependencies: []

collections:
  - community.general
  - ansible.posix
  - community.docker
  - community.crypto
