---
# Global Variables
timezone: "Europe/Sofia"
ansible_python_interpreter: /usr/bin/python3

#NTP
ntp_servers:
  - pool.ntp.org
  - time.google.com
  - time.cloudflare.com
  - time.nist.gov
ntp_pool_servers:
  - "0.pool.ntp.org"
  - "1.pool.ntp.org"
  - "2.pool.ntp.org"
  - "3.pool.ntp.org"
ntp_pool_maxsources: 4
ntp_enabled: true
ntp_poll_interval_min: 32
ntp_poll_interval_max: 2048
ntp_connection_retry: 30
ntp_save_interval: 60
ntp_makestep_threshold: 1.0
ntp_makestep_limit: 3
ntp_log_level: "measurements statistics tracking"
ntp_statistics_enabled: false
ntp_server_enabled: false
ntp_security_hardening: true

## Rate limiting
ntp_rate_limit:
  interval: 3
  burst: 8

# SSH Configuration
ssh_port: 22
ssh_permit_root_login: "no"
ssh_password_authentication: "no"
ssh_pubkey_authentication: "yes"
ssh_challenge_response_auth: "no"
ssh_x11_forwarding: "no"
ssh_max_auth_tries: 3
ssh_max_sessions: 2
ssh_client_alive_interval: 300
ssh_client_alive_count_max: 2
ssh_protocol: 2
authorized_keys_exclusive: true # Set to true to remove all unlisted keys
backup_keys: true # Set to false to skip backups

# Firewall Settings
firewall_enabled: true
firewall_reset_before_config: true
firewall_default_incoming: "deny"
firewall_default_outgoing: "allow"
firewall_allow_ssh_from_anywhere: true
firewall_allow_http: true
firewall_allow_https: true

# Fail2ban Configuration
fail2ban_enabled: true
fail2ban_bantime: 3600
fail2ban_findtime: 600
fail2ban_maxretry: 5
fail2ban_ssh_maxretry: 3
fail2ban_backend: "systemd"

# TCP Wrappers
tcp_wrappers_enabled: true
tcp_wrappers_allow_private_networks: false

# System Security
enable_unattended_upgrades: true
configure_sysctl_security: true
disable_ipv6: true

# Security Settings
automatic_security_updates: true
unattended_upgrades: true

# Monitoring
monitoring_enabled: true
log_retention_days: 30
configure_custom_logrotate: true

# System Limits
configure_system_limits: true
max_open_files: 65536
max_processes: 32768

# Common packages
common_packages:
  - curl
  - wget
  - vim
  - htop
  - tree
  - unzip
  - git
  - jq
  - btop

# Network
default_network_interface: "eth0" # Network interface name
network_rollback_timeout: 300 # 5 minutes to rollback if connectivity lost
network_mtu: 1500 # MTU size
network_config_mode: "static"
network_wake_on_lan: true # Wake on LAN
network_enable_ipv6: true # Enable IPv6
network_link_local: [] # Link-local addresses
network_accept_ra: true # Accept router advertisements
network_dns_servers:
  - "9.9.9.9"
  - "1.1.1.1"
  - "37.114.63.170"
network_netmask: "24" #"255.255.255.0" # Subnet mask (CIDR or dotted decimal)
network_ipv6_enabled: false

# Tailscale configuration variables
tailscale_accept_dns: true
tailscale_accept_routes: true
tailscale_advertise_exit_node: false
tailscale_snat_subnet_routes: true
tailscale_ssh: true
    
# Service configuration
tailscale_service_enabled: true
tailscale_service_state: started
tailscale_log_level: "info"  # debug, info, warn, error
tailscale_timeout: 60
  
    
# Common variables
tailscale_package_name: "tailscale"
tailscale_daemon_port: 41641