---
# ===========================================
# Proxmox VE Role - Handlers
# Managed by Ansible
# ===========================================

- name: restart pveproxy
  ansible.builtin.systemd:
    name: pveproxy
    state: restarted
  listen: restart pveproxy

- name: restart pvedaemon
  ansible.builtin.systemd:
    name: pvedaemon
    state: restarted
  listen: restart pvedaemon

- name: restart pvestatd
  ansible.builtin.systemd:
    name: pvestatd
    state: restarted
  listen: restart pvestatd

- name: restart pve-cluster
  ansible.builtin.systemd:
    name: pve-cluster
    state: restarted
  listen: restart pve-cluster

- name: restart corosync
  ansible.builtin.systemd:
    name: corosync
    state: restarted
  listen: restart corosync

- name: restart pve-firewall
  ansible.builtin.systemd:
    name: pve-firewall
    state: restarted
  listen: restart pve-firewall

- name: reload networking
  ansible.builtin.systemd:
    name: networking
    state: reloaded
  listen: reload networking

- name: restart sshd
  ansible.builtin.systemd:
    name: sshd
    state: restarted
  listen: restart sshd

- name: restart fail2ban
  ansible.builtin.systemd:
    name: fail2ban
    state: restarted
  listen: restart fail2ban

- name: restart auditd
  ansible.builtin.service:
    name: auditd
    state: restarted
  listen: restart auditd

- name: restart postfix
  ansible.builtin.systemd:
    name: postfix
    state: restarted
  listen: restart postfix

- name: restart rsyslog
  ansible.builtin.systemd:
    name: rsyslog
    state: restarted
  listen: restart rsyslog

- name: update grub
  ansible.builtin.command: update-grub
  listen: update grub

- name: update aliases
  ansible.builtin.command: newaliases
  listen: update aliases

- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  listen: reload systemd
