---
# Configure firewall for cAdvisor

- name: Configure UFW firewall (Debian)
  community.general.ufw:
    rule: allow
    port: "{{ cadvisor_port }}"
    proto: tcp
    comment: cAdvisor monitoring
  when: ansible_os_family == "Debian"
  tags: [cadvisor, firewall]

- name: Configure firewalld (RHEL)
  ansible.posix.firewalld:
    port: "{{ cadvisor_port }}/tcp"
    permanent: true
    state: enabled
    zone: "{{ cadvisor_firewall_zone }}"
    immediate: true
  when: ansible_os_family == "RedHat"
  tags: [cadvisor, firewall]
