---
# Default variables for tailscale role

# Package name
tailscale_package_name: "tailscale"

# Required packages (OS-specific)
tailscale_required_packages:
  - curl
  - ca-certificates

# Service configuration
tailscale_service_enabled: true
tailscale_service_state: started
tailscale_daemon_port: 41641
tailscale_log_level: 1  # info

# Tailscale up arguments
tailscale_accept_dns: true
tailscale_accept_routes: false
tailscale_advertise_exit_node: false
tailscale_advertise_routes: []
tailscale_snat_subnet_routes: false
tailscale_ssh: true
tailscale_timeout: 60

# Authentication
tailscale_auth_key: ""  # Should be set in vault or host_vars
tailscale_require_auth_key: false

# Daemon configuration paths (OS-specific - set in vars/)
# tailscale_daemon_config_path: "/etc/default/tailscaled"  # Debian
# tailscale_daemon_config_path: "/etc/sysconfig/tailscaled"  # RHEL
