---
# tasks file for nfs

- name: Include OS-specific variables
  ansible.builtin.include_vars: "{{ ansible_os_family | lower }}.yml"

- name: Validate NFS mode
  ansible.builtin.assert:
    that:
      - nfs_mode in ['server', 'client', 'both']
    fail_msg: "nfs_mode must be one of: server, client, both"
    success_msg: "NFS mode is valid: {{ nfs_mode }}"

- name: Include NFS server tasks
  ansible.builtin.include_tasks: server.yml
  when: nfs_mode in ['server', 'both']

- name: Include NFS client tasks
  ansible.builtin.include_tasks: client.yml
  when: nfs_mode in ['client', 'both']

- name: Configure NFS idmapd
  ansible.builtin.template:
    src: idmapd.conf.j2
    dest: "{{ nfs_idmapd_config_file }}"
    owner: root
    group: root
    mode: '0644'
  notify: Restart nfs idmapd
  when: nfs_version == 4
