---
all:
  children:
    debian:
      hosts:
        ironwolf.local:
          ansible_host: 192.168.50.207
          ansible_user: root
      vars:
        ansible_python_interpreter: /usr/bin/python3
        package_manager: apt
