---
# Install Mimir from binary

- name: Create Mimir directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: mimir
    group: mimir
    mode: '0755'
  loop:
    - "{{ mimir_config_dir }}"
    - "{{ mimir_data_dir }}"
    - "{{ mimir_storage_filesystem_dir }}"
    - "{{ mimir_blocks_storage_tsdb_dir }}"

- name: Download Mimir binary
  ansible.builtin.get_url:
    url: "{{ mimir_binary_url }}"
    dest: "{{ grafana_binary_install_dir }}/mimir"
    mode: '0755'
    owner: mimir
    group: mimir

- name: Deploy Mimir configuration
  ansible.builtin.template:
    src: mimir.yml.j2
    dest: "{{ mimir_config_dir }}/mimir.yml"
    owner: mimir
    group: mimir
    mode: '0644'
  notify: Restart mimir

- name: Deploy Mimir systemd service file
  ansible.builtin.template:
    src: mimir.service.j2
    dest: /etc/systemd/system/mimir.service
    mode: '0644'
  notify: Restart mimir

- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true

- name: Enable and start Mimir service
  ansible.builtin.systemd:
    name: mimir
    enabled: "{{ mimir_service_enabled }}"
    state: "{{ mimir_service_state }}"
