---
# Tailscale role - VPN mesh network configuration
- name: Include OS-specific variables
  ansible.builtin.include_vars: "{{ ansible_os_family | lower }}.yml"
  tags: [tailscale, always]

- name: Include Debian installation tasks
  ansible.builtin.include_tasks: debian.yml
  when: ansible_os_family == "Debian"
  tags: [tailscale, install, debian]

- name: Include RHEL installation tasks
  ansible.builtin.include_tasks: rhel.yml
  when: ansible_os_family == "RedHat"
  tags: [tailscale, install, rhel]

- name: Install required packages for Tailscale
  ansible.builtin.package:
    name: "{{ tailscale_required_packages }}"
    state: present
  tags: [tailscale, install]

- name: Install Tailscale package
  ansible.builtin.package:
    name: "{{ tailscale_package_name }}"
    state: present
  tags: [tailscale, install]

- name: Include configuration tasks
  ansible.builtin.include_tasks: configure.yml
  tags: [tailscale, configure]

- name: Include authentication tasks
  ansible.builtin.include_tasks: auth.yml
  tags: [tailscale, auth]
