---
- name: Converge
  hosts: all
  become: true

  pre_tasks:
    - name: Update apt cache (Debian)
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      when: ansible_os_family == 'Debian'

    - name: Update dnf cache (RedHat)
      ansible.builtin.dnf:
        update_cache: true
      when: ansible_os_family == 'RedHat'

  roles:
    - role: prometheus_stack
