---
galaxy_info:
  author: Sidney
  description: Install and configure cAdvisor container monitoring
  company: Home Lab
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
    - name: Debian
      versions:
        - bullseye
        - bookworm
    - name: EL
      versions:
        - "8"
        - "9"
  galaxy_tags:
    - monitoring
    - cadvisor
    - containers
    - docker
    - metrics

dependencies: []
