---
# Verification tasks

- name: Wait for Prometheus to be ready
  ansible.builtin.uri:
    url: "{{ 'https' if prometheus_stack_enable_tls else 'http' }}://localhost:{{ prometheus_web_listen_address.split(':')[1] | default('9090') }}/-/ready"
    method: GET
    status_code: 200
    validate_certs: false
  retries: 5
  delay: 10
  register: prometheus_ready
  until: prometheus_ready.status == 200
  when: prometheus_stack_install_prometheus | bool
  tags:
    - prometheus

- name: Verify Prometheus configuration is loaded
  ansible.builtin.uri:
    url: "{{ 'https' if prometheus_stack_enable_tls else 'http' }}://localhost:{{ prometheus_web_listen_address.split(':')[1] | default('9090') }}/api/v1/status/config"
    method: GET
    status_code: 200
    validate_certs: false
  register: prometheus_config_check
  when: prometheus_stack_install_prometheus | bool
  tags:
    - prometheus

- name: Wait for Alertmanager to be ready
  ansible.builtin.uri:
    url: "{{ 'https' if prometheus_stack_enable_tls else 'http' }}://localhost:{{ alertmanager_web_listen_address.split(':')[1] | default('9093') }}/-/ready"
    method: GET
    status_code: 200
    validate_certs: false
  retries: 5
  delay: 10
  register: alertmanager_ready
  until: alertmanager_ready.status == 200
  when: prometheus_stack_install_alertmanager | bool
  tags:
    - alertmanager

- name: Verify Node Exporter is responding
  ansible.builtin.uri:
    url: "http://localhost:{{ node_exporter_web_listen_address.split(':')[1] | default('9100') }}/metrics"
    method: GET
    status_code: 200
  retries: 3
  delay: 5
  register: node_exporter_check
  until: node_exporter_check.status == 200
  when: prometheus_stack_install_node_exporter | bool
  tags:
    - node_exporter

- name: Verify Blackbox Exporter is responding
  ansible.builtin.uri:
    url: "http://localhost:{{ blackbox_exporter_web_listen_address.split(':')[1] | default('9115') }}/metrics"
    method: GET
    status_code: 200
  retries: 3
  delay: 5
  register: blackbox_exporter_check
  until: blackbox_exporter_check.status == 200
  when: prometheus_stack_install_blackbox_exporter | bool
  tags:
    - blackbox_exporter

- name: Verify systemd services are running
  ansible.builtin.service_facts:

- name: Check Prometheus service status
  ansible.builtin.assert:
    that:
      - ansible_facts.services['prometheus.service'].state == 'running'
    fail_msg: "Prometheus service is not running"
    success_msg: "Prometheus service is running"
  when: prometheus_stack_install_prometheus | bool

- name: Check Alertmanager service status
  ansible.builtin.assert:
    that:
      - ansible_facts.services['alertmanager.service'].state == 'running'
    fail_msg: "Alertmanager service is not running"
    success_msg: "Alertmanager service is running"
  when: prometheus_stack_install_alertmanager | bool

- name: Check Node Exporter service status
  ansible.builtin.assert:
    that:
      - ansible_facts.services['node_exporter.service'].state == 'running'
    fail_msg: "Node Exporter service is not running"
    success_msg: "Node Exporter service is running"
  when: prometheus_stack_install_node_exporter | bool

- name: Check Blackbox Exporter service status
  ansible.builtin.assert:
    that:
      - ansible_facts.services['blackbox_exporter.service'].state == 'running'
    fail_msg: "Blackbox Exporter service is not running"
    success_msg: "Blackbox Exporter service is running"
  when: prometheus_stack_install_blackbox_exporter | bool

- name: Display verification results
  ansible.builtin.debug:
    msg:
      - "Prometheus Stack Verification Complete"
      - "Prometheus: {{ 'OK' if (prometheus_stack_install_prometheus and prometheus_ready.status == 200) else 'SKIPPED' }}"
      - "Alertmanager: {{ 'OK' if (prometheus_stack_install_alertmanager and alertmanager_ready.status == 200) else 'SKIPPED' }}"
      - "Node Exporter: {{ 'OK' if (prometheus_stack_install_node_exporter and node_exporter_check.status == 200) else 'SKIPPED' }}"
      - "Blackbox Exporter: {{ 'OK' if (prometheus_stack_install_blackbox_exporter and blackbox_exporter_check.status == 200) else 'SKIPPED' }}"
