---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ubuntu-ntp
    image: geerlingguy/docker-ubuntu2204-ansible:latest
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
  - name: debian-ntp
    image: geerlingguy/docker-debian12-ansible:latest
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  playbooks:
    converge: converge.yml
  inventory:
    host_vars:
      ubuntu-ntp:
        ansible_python_interpreter: /usr/bin/python3
        timezone: "America/New_York"
      debian-ntp:
        ansible_python_interpreter: /usr/bin/python3
        timezone: "Europe/London"
verifier:
  name: ansible
