---
# Molecule verification tests for ntp role
- name: Verify
  hosts: all
  gather_facts: true
  tasks:
    - name: Check if systemd-timesyncd is installed (Debian)
      ansible.builtin.command: systemctl status systemd-timesyncd
      register: timesyncd_status
      changed_when: false
      failed_when: false
      when: ansible_os_family == "Debian"

    - name: Check if chronyd is installed (RHEL)
      ansible.builtin.command: systemctl status chronyd
      register: chronyd_status
      changed_when: false
      failed_when: false
      when: ansible_os_family == "RedHat"

    - name: Verify NTP service is running (Debian)
      ansible.builtin.assert:
        that:
          - timesyncd_status.rc == 0
          - "'active' in timesyncd_status.stdout"
        fail_msg: "systemd-timesyncd is not running"
        success_msg: "systemd-timesyncd is active"
      when: ansible_os_family == "Debian"

    - name: Verify NTP service is running (RHEL)
      ansible.builtin.assert:
        that:
          - chronyd_status.rc == 0
          - "'active' in chronyd_status.stdout"
        fail_msg: "chronyd is not running"
        success_msg: "chronyd is active"
      when: ansible_os_family == "RedHat"

    - name: Check timezone configuration
      ansible.builtin.command: timedatectl show --property=Timezone --value
      register: configured_timezone
      changed_when: false

    - name: Verify timezone is set correctly
      ansible.builtin.assert:
        that:
          - configured_timezone.stdout == timezone
        fail_msg: "Timezone is {{ configured_timezone.stdout }}, expected {{ timezone }}"
        success_msg: "Timezone is correctly set to {{ timezone }}"

    - name: Display verification results
      ansible.builtin.debug:
        msg: |
          NTP role verification complete!
          Timezone: {{ configured_timezone.stdout }}
          NTP Service: {{ 'systemd-timesyncd' if ansible_os_family == 'Debian' else 'chronyd' }}
