---
# Molecule verification tests for docker role
- name: Verify
  hosts: all
  gather_facts: true
  tasks:
    - name: Check if Docker is installed
      ansible.builtin.command: docker --version
      register: docker_version_check
      changed_when: false
      failed_when: docker_version_check.rc != 0

    - name: Check if Docker Compose is installed
      ansible.builtin.command: docker compose version
      register: docker_compose_check
      changed_when: false
      failed_when: docker_compose_check.rc != 0

    - name: Check if Docker service is running
      ansible.builtin.systemd:
        name: docker
      register: docker_service
      failed_when: docker_service.status.ActiveState != "active"

    - name: Verify Docker daemon configuration exists
      ansible.builtin.stat:
        path: /etc/docker/daemon.json
      register: daemon_config
      failed_when: not daemon_config.stat.exists

    - name: Verify Docker seccomp profile exists
      ansible.builtin.stat:
        path: /etc/docker/seccomp.json
      register: seccomp_profile
      failed_when: not seccomp_profile.stat.exists

    - name: Display Docker version
      ansible.builtin.debug:
        msg: |
          Docker version: {{ docker_version_check.stdout }}
          Docker Compose: {{ docker_compose_check.stdout }}
          Docker service state: {{ docker_service.status.ActiveState }}
