---
# Molecule converge playbook for ntp role
- name: Converge
  hosts: all
  become: true
  gather_facts: true

  pre_tasks:
    - name: Update apt cache (Debian)
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      when: ansible_os_family == "Debian"

  roles:
    - role: ntp
      vars:
        ntp_enabled: true
        ntp_security_hardening: true
        firewall_enabled: false  # Disable firewall in tests
