---
# Molecule verification tests for tailscale role
- name: Verify
  hosts: all
  gather_facts: true
  tasks:
    - name: Check if Tailscale is installed
      ansible.builtin.command: tailscale --version
      register: tailscale_version_check
      changed_when: false
      failed_when: tailscale_version_check.rc != 0

    - name: Check if tailscaled binary exists
      ansible.builtin.stat:
        path: /usr/sbin/tailscaled
      register: tailscaled_binary
      failed_when: not tailscaled_binary.stat.exists

    - name: Check if tailscale service is installed
      ansible.builtin.systemd:
        name: tailscaled
      register: tailscale_service
      failed_when: tailscale_service.status is not defined

    - name: Verify repository configuration exists (Debian)
      ansible.builtin.stat:
        path: /etc/apt/sources.list.d/tailscale.list
      register: tailscale_repo_debian
      failed_when: not tailscale_repo_debian.stat.exists
      when: ansible_os_family == "Debian"

    - name: Verify daemon config exists
      ansible.builtin.stat:
        path: "{{ '/etc/default/tailscaled' if ansible_os_family == 'Debian' else '/etc/sysconfig/tailscaled' }}"
      register: daemon_config
      failed_when: not daemon_config.stat.exists

    - name: Display verification results
      ansible.builtin.debug:
        msg: |
          Tailscale role verification complete!
          Tailscale version: {{ tailscale_version_check.stdout }}
          Binary exists: {{ tailscaled_binary.stat.exists }}
          Service installed: {{ tailscale_service.status is defined }}
