---
- name: Verify NFS servers
  hosts: nfs_servers
  become: true
  tasks:
    - name: Check if NFS server service is running
      ansible.builtin.service_facts:

    - name: Verify NFS server service is active (Debian)
      ansible.builtin.assert:
        that:
          - "'nfs-server.service' in services or 'nfs-kernel-server.service' in services"
          - "services['nfs-kernel-server.service'].state == 'running'"
        fail_msg: "NFS server service is not running"
        success_msg: "NFS server service is running"
      when: ansible_os_family == 'Debian'

    - name: Verify NFS server service is active (RedHat)
      ansible.builtin.assert:
        that:
          - "'nfs-server.service' in services"
          - "services['nfs-server.service'].state == 'running'"
        fail_msg: "NFS server service is not running"
        success_msg: "NFS server service is running"
      when: ansible_os_family == 'RedHat'

    - name: Check if exports file exists
      ansible.builtin.stat:
        path: /etc/exports
      register: exports_file

    - name: Verify exports file exists
      ansible.builtin.assert:
        that:
          - exports_file.stat.exists
        fail_msg: "/etc/exports does not exist"
        success_msg: "/etc/exports exists"

    - name: Check if NFS export directory exists
      ansible.builtin.stat:
        path: /srv/nfs/shared
      register: nfs_export_dir

    - name: Verify NFS export directory exists
      ansible.builtin.assert:
        that:
          - nfs_export_dir.stat.exists
          - nfs_export_dir.stat.isdir
        fail_msg: "NFS export directory does not exist"
        success_msg: "NFS export directory exists"

    - name: Get active NFS exports
      ansible.builtin.command: exportfs -v
      register: nfs_exports_output
      changed_when: false

    - name: Verify NFS exports are active
      ansible.builtin.assert:
        that:
          - "'/srv/nfs/shared' in nfs_exports_output.stdout"
        fail_msg: "NFS exports are not configured correctly"
        success_msg: "NFS exports are configured correctly"

- name: Verify NFS clients
  hosts: nfs_clients
  become: true
  tasks:
    - name: Check if NFS client packages are installed (Debian)
      ansible.builtin.package_facts:
        manager: apt
      when: ansible_os_family == 'Debian'

    - name: Check if NFS client packages are installed (RedHat)
      ansible.builtin.package_facts:
        manager: rpm
      when: ansible_os_family == 'RedHat'

    - name: Verify nfs-common package is installed (Debian)
      ansible.builtin.assert:
        that:
          - "'nfs-common' in ansible_facts.packages"
        fail_msg: "nfs-common package is not installed"
        success_msg: "nfs-common package is installed"
      when: ansible_os_family == 'Debian'

    - name: Verify nfs-utils package is installed (RedHat)
      ansible.builtin.assert:
        that:
          - "'nfs-utils' in ansible_facts.packages"
        fail_msg: "nfs-utils package is not installed"
        success_msg: "nfs-utils package is installed"
      when: ansible_os_family == 'RedHat'

    - name: Check if rpcbind is running (RedHat)
      ansible.builtin.service_facts:
      when: ansible_os_family == 'RedHat'

    - name: Verify rpcbind service is active (RedHat)
      ansible.builtin.assert:
        that:
          - "'rpcbind.service' in services"
          - "services['rpcbind.service'].state == 'running'"
        fail_msg: "rpcbind service is not running"
        success_msg: "rpcbind service is running"
      when: ansible_os_family == 'RedHat'
