---
# Prerequisites for k3s installation

- name: Install required packages
  ansible.builtin.package:
    name: "{{ k3s_system_packages }}"
    state: present
  tags: [k3s, prerequisites]

- name: Ensure kernel modules are loaded
  community.general.modprobe:
    name: "{{ item }}"
    state: present
  loop:
    - br_netfilter
    - overlay
  tags: [k3s, prerequisites]

- name: Configure sysctl for Kubernetes
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    reload: true
    sysctl_file: /etc/sysctl.d/99-kubernetes.conf
  loop:
    - name: net.bridge.bridge-nf-call-iptables
      value: "1"
    - name: net.bridge.bridge-nf-call-ip6tables
      value: "1"
    - name: net.ipv4.ip_forward
      value: "1"
  tags: [k3s, prerequisites]

- name: Create k3s configuration directory
  ansible.builtin.file:
    path: "{{ k3s_config_dir }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  tags: [k3s, prerequisites]

- name: Check if k3s is already installed
  ansible.builtin.stat:
    path: "{{ k3s_install_dir }}/k3s"
  register: k3s_binary
  tags: [k3s, prerequisites]
