---
# Debian/Ubuntu unattended-upgrades configuration
- name: Install unattended-upgrades
  ansible.builtin.package:
    name: unattended-upgrades
    state: present
  tags: [security, auto_updates, debian]

- name: Configure automatic updates
  ansible.builtin.template:
    src: 20auto-upgrades.j2
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    owner: root
    group: root
    mode: '0644'
    backup: true
  tags: [security, auto_updates, debian]

- name: Configure unattended-upgrades settings
  ansible.builtin.template:
    src: 50unattended-upgrades.j2
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    owner: root
    group: root
    mode: '0644'
    backup: true
  tags: [security, auto_updates, debian]
