---
# Fail2ban configuration tasks
- name: Install fail2ban
  ansible.builtin.package:
    name: fail2ban
    state: present
  tags: [security, fail2ban]

- name: Configure fail2ban jail settings
  ansible.builtin.template:
    src: jail.local.j2
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: '0644'
    backup: true
  notify: Restart fail2ban
  tags: [security, fail2ban]

- name: Ensure fail2ban is enabled and started
  ansible.builtin.systemd:
    name: fail2ban
    enabled: true
    state: started
  tags: [security, fail2ban]
