---
all:
  children:
    debian:
      hosts:
        ironwolf:
          timezone: "Europe/Sofia"
          ansible_host: "192.168.50.115"
          ansible_user: "sidney"
          network_static_ip: "192.168.50.115"
          network_gateway: "192.168.50.1"
          hostname_fqdn: "ansblt01.graylock.eu"
          network_interface: "ens18"
          whitelist_ips:
            - "192.168.50.0/24"
            - "10.10.10.0/24"
            - "37.114.63.170"
            - "91.216.57.29"
            - "85.14.55.128"
            - "100.67.7.113"
            - "100.93.54.62"
            - "100.103.91.2"
            - "100.96.98.101"
            - "100.73.121.62"
          tailscale_advertise_routes: ["192.168.50.0/24"] # e.g., ["10.0.0.0/8", "192.168.0.0/16"]
