---
# Configure firewall for k3s

- name: Determine required firewall ports
  ansible.builtin.set_fact:
    k3s_required_ports: >-
      {{
        (k3s_server_enabled | bool) | ternary(k3s_server_firewall_ports, []) +
        (k3s_agent_enabled | bool) | ternary(k3s_agent_firewall_ports, []) +
        (k3s_cni == 'calico') | ternary(calico_firewall_ports, [])
      }}
  tags: [k3s, firewall]

- name: Configure UFW firewall (Debian)
  community.general.ufw:
    rule: allow
    port: "{{ item.split('/')[0] }}"
    proto: "{{ item.split('/')[1] }}"
    comment: "k3s - {{ item }}"
  loop: "{{ k3s_required_ports }}"
  when: ansible_os_family == "Debian"
  tags: [k3s, firewall]

- name: Configure firewalld (RHEL)
  ansible.posix.firewalld:
    port: "{{ item }}"
    permanent: true
    state: enabled
    zone: "{{ k3s_firewall_zone }}"
    immediate: true
  loop: "{{ k3s_required_ports }}"
  when: ansible_os_family == "RedHat"
  tags: [k3s, firewall]
