---
# Handlers for ntp role
- name: Restart chronyd
  ansible.builtin.systemd:
    name: chronyd
    state: restarted
  when:
    - ansible_os_family == "RedHat"
    - ntp_enabled | default(true)

- name: Restart systemd-timesyncd
  ansible.builtin.systemd:
    name: systemd-timesyncd
    state: restarted
  when:
    - ansible_os_family == "Debian"
    - ntp_enabled | default(true)
