---
# Docker Installation Playbook (Using Role)
# This playbook uses the docker role for installation
- name: Install and Configure Docker
  hosts: all
  become: true
  gather_facts: true

  roles:
    - common
    - docker

  post_tasks:
    - name: Display docker and docker compose versions
      ansible.builtin.debug:
        msg: |
          Docker installation complete!
          Run 'docker --version' and 'docker compose version' to verify.
