---
- name: Prepare
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Install required packages (Debian)
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - software-properties-common
        state: present
        update_cache: true
      when: ansible_os_family == "Debian"

    - name: Install required packages (RedHat)
      ansible.builtin.yum:
        name:
          - ca-certificates
          - curl
          - gnupg2
        state: present
      when: ansible_os_family == "RedHat"

    - name: Set vm.max_map_count for Elasticsearch
      ansible.posix.sysctl:
        name: vm.max_map_count
        value: "262144"
        state: present
        reload: true
