---
# RedHat-specific variables for Wazuh

wazuh_required_packages:
  - curl
  - gnupg

wazuh_manager_package: wazuh-manager
wazuh_indexer_package: wazuh-indexer
wazuh_dashboard_package: wazuh-dashboard
wazuh_agent_package: wazuh-agent

# OpenSCAP packages
wazuh_openscap_packages:
  - openscap-scanner
  - scap-security-guide

# Osquery package
wazuh_osquery_package: osquery
