---
# Install Trivy from binary release

- name: Determine latest Trivy version
  ansible.builtin.uri:
    url: https://api.github.com/repos/aquasecurity/trivy/releases/latest
    return_content: true
  register: trivy_latest_release
  when: trivy_version == ""
  tags: [trivy, install, binary]

- name: Set Trivy version to latest
  ansible.builtin.set_fact:
    trivy_version: "{{ trivy_latest_release.json.tag_name }}"
  when: trivy_version == ""
  tags: [trivy, install, binary]

- name: Download Trivy binary
  ansible.builtin.get_url:
    url: "{{ trivy_binary_url }}"
    dest: /tmp/trivy.tar.gz
    mode: "0644"
    timeout: 60
  tags: [trivy, install, binary]

- name: Extract Trivy binary
  ansible.builtin.unarchive:
    src: /tmp/trivy.tar.gz
    dest: "{{ trivy_install_dir }}"
    remote_src: true
    creates: "{{ trivy_binary_path }}"
    mode: "0755"
  tags: [trivy, install, binary]

- name: Remove temporary archive
  ansible.builtin.file:
    path: /tmp/trivy.tar.gz
    state: absent
  tags: [trivy, install, binary]

- name: Ensure Trivy binary is executable
  ansible.builtin.file:
    path: "{{ trivy_binary_path }}"
    mode: "0755"
    owner: root
    group: root
  tags: [trivy, install, binary]
