---
# k3s Cluster Deployment Playbook (Using Community Role)
# Uses xanmanning.k3s for k3s cluster deployment
- name: Deploy k3s Kubernetes Cluster - Server Nodes
  hosts: k3s_servers
  become: true
  gather_facts: true
  serial: 1

  vars:
    k3s_become: true
    k3s_state: installed
    k3s_install_hard_links: true
    k3s_server:
      node-taint:
        - "CriticalAddonsOnly=true:NoExecute"
      tls-san:
        - "{{ ansible_default_ipv4.address }}"
      disable:
        - traefik
        - servicelb

  pre_tasks:
    - name: Display server deployment information
      ansible.builtin.debug:
        msg: |
          === Deploying k3s Server to {{ inventory_hostname }} ===
          OS: {{ ansible_distribution }} {{ ansible_distribution_version }}

  roles:
    - role: xanmanning.k3s

  post_tasks:
    - name: Display server information
      ansible.builtin.debug:
        msg: |
          Server {{ inventory_hostname }} deployed successfully
          API: https://{{ ansible_default_ipv4.address }}:6443

- name: Deploy k3s Kubernetes Cluster - Agent Nodes
  hosts: k3s_agents
  become: true
  gather_facts: true

  vars:
    k3s_become: true
    k3s_state: installed
    k3s_control_node: false
    k3s_server_url: "https://{{ hostvars[groups['k3s_servers'][0]]['ansible_default_ipv4']['address'] }}:6443"

  pre_tasks:
    - name: Display agent deployment information
      ansible.builtin.debug:
        msg: |
          === Deploying k3s Agent to {{ inventory_hostname }} ===
          OS: {{ ansible_distribution }} {{ ansible_distribution_version }}
          Server: {{ k3s_server_url }}

  roles:
    - role: xanmanning.k3s

  post_tasks:
    - name: Display agent deployment status
      ansible.builtin.debug:
        msg: "Agent {{ inventory_hostname }} deployed successfully"

- name: Verify k3s Cluster
  hosts: k3s_servers[0]
  become: true
  gather_facts: false

  tasks:
    - name: Wait for all nodes to join
      ansible.builtin.command:
        cmd: /usr/local/bin/k3s kubectl get nodes
      register: all_nodes
      until: all_nodes.stdout_lines | length >= (groups['k3s_servers'] | length + groups['k3s_agents'] | default([]) | length)
      retries: 30
      delay: 10
      changed_when: false

    - name: Display cluster status
      ansible.builtin.debug:
        msg: |
          === k3s Cluster Deployment Complete ===
          Total Nodes: {{ all_nodes.stdout_lines | length - 1 }}
          Servers: {{ groups['k3s_servers'] | length }}
          Agents: {{ groups['k3s_agents'] | default([]) | length }}

          Cluster Nodes:
          {{ all_nodes.stdout }}

    - name: Get all pods
      ansible.builtin.command:
        cmd: /usr/local/bin/k3s kubectl get pods -A
      register: all_pods
      changed_when: false

    - name: Display pod status
      ansible.builtin.debug:
        var: all_pods.stdout_lines
