---
# Configure and install CrowdSec bouncers

- name: Install firewall bouncer
  when: crowdsec_bouncers | selectattr('name', 'equalto', 'firewall') | selectattr('enabled', 'equalto', true) | list | length > 0
  block:
    - name: Install firewall bouncer package
      ansible.builtin.package:
        name: crowdsec-firewall-bouncer
        state: present

    - name: Generate firewall bouncer API key
      ansible.builtin.command:
        cmd: "{{ _cscli_binary }} bouncers add firewall-bouncer"
      register: crowdsec_firewall_bouncer_key
      changed_when: "'already exists' not in crowdsec_firewall_bouncer_key.stderr"
      failed_when:
        - crowdsec_firewall_bouncer_key.rc != 0
        - "'already exists' not in crowdsec_firewall_bouncer_key.stderr"

    - name: Extract firewall bouncer API key
      ansible.builtin.set_fact:
        crowdsec_firewall_bouncer_api_key: "{{ crowdsec_firewall_bouncer_key.stdout_lines[-1] if crowdsec_firewall_bouncer_key.changed else crowdsec_bouncer_keys.firewall | default('') }}"
      when: crowdsec_firewall_bouncer_key.changed or crowdsec_bouncer_keys.firewall is defined

    - name: Configure firewall bouncer
      ansible.builtin.template:
        src: crowdsec-firewall-bouncer.yaml.j2
        dest: "{{ _crowdsec_firewall_bouncer_config }}"
        owner: root
        group: root
        mode: '0600'
      notify:
        - Restart firewall bouncer

    - name: Ensure firewall bouncer service is enabled and started
      ansible.builtin.service:
        name: "{{ _crowdsec_firewall_bouncer_service }}"
        enabled: true
        state: started

- name: Install Traefik bouncer
  when: crowdsec_bouncers | selectattr('name', 'equalto', 'traefik') | selectattr('enabled', 'equalto', true) | list | length > 0
  block:
    - name: Check if Traefik is installed
      ansible.builtin.stat:
        path: /usr/local/bin/traefik
      register: crowdsec_traefik_binary

    - name: Install Traefik bouncer package
      ansible.builtin.package:
        name: crowdsec-traefik-bouncer
        state: present
      when: crowdsec_traefik_binary.stat.exists

    - name: Generate Traefik bouncer API key
      ansible.builtin.command:
        cmd: "{{ _cscli_binary }} bouncers add traefik-bouncer"
      register: crowdsec_traefik_bouncer_key
      changed_when: "'already exists' not in crowdsec_traefik_bouncer_key.stderr"
      failed_when:
        - crowdsec_traefik_bouncer_key.rc != 0
        - "'already exists' not in crowdsec_traefik_bouncer_key.stderr"
      when: crowdsec_traefik_binary.stat.exists

    - name: Extract Traefik bouncer API key
      ansible.builtin.set_fact:
        crowdsec_traefik_bouncer_api_key: "{{ crowdsec_traefik_bouncer_key.stdout_lines[-1] if crowdsec_traefik_bouncer_key.changed else crowdsec_bouncer_keys.traefik | default('') }}"
      when:
        - crowdsec_traefik_binary.stat.exists
        - crowdsec_traefik_bouncer_key.changed or crowdsec_bouncer_keys.traefik is defined

    - name: Configure Traefik bouncer
      ansible.builtin.template:
        src: crowdsec-traefik-bouncer.yaml.j2
        dest: "{{ _crowdsec_traefik_bouncer_config }}"
        owner: root
        group: root
        mode: '0600'
      when: crowdsec_traefik_binary.stat.exists
      notify:
        - Restart traefik bouncer

    - name: Ensure Traefik bouncer service is enabled and started
      ansible.builtin.service:
        name: "{{ _crowdsec_traefik_bouncer_service }}"
        enabled: true
        state: started
      when: crowdsec_traefik_binary.stat.exists

- name: Install blocklist collections
  when: crowdsec_bouncers | selectattr('name', 'equalto', 'blocklist') | selectattr('enabled', 'equalto', true) | list | length > 0
  block:
    - name: Get blocklist configuration
      ansible.builtin.set_fact:
        crowdsec_blocklist_config: "{{ crowdsec_bouncers | selectattr('name', 'equalto', 'blocklist') | first }}"

    - name: Install blocklist collections
      ansible.builtin.command:
        cmd: "{{ _cscli_binary }} collections install {{ item }}"
      loop: "{{ crowdsec_blocklist_config.collections | default([]) }}"
      register: crowdsec_blocklist_install
      changed_when: "'already installed' not in crowdsec_blocklist_install.stdout"
      failed_when:
        - crowdsec_blocklist_install.rc != 0
        - "'already installed' not in crowdsec_blocklist_install.stdout"
        - "'can\\'t find' not in crowdsec_blocklist_install.stderr"

- name: List installed bouncers
  ansible.builtin.command:
    cmd: "{{ _cscli_binary }} bouncers list"
  register: crowdsec_bouncers_list
  changed_when: false

- name: Display installed bouncers
  ansible.builtin.debug:
    var: crowdsec_bouncers_list.stdout_lines
