---
# Configure AppSec (Application Security) for CrowdSec

- name: Install AppSec collections
  ansible.builtin.command:
    cmd: "{{ _cscli_binary }} collections install {{ item }}"
  loop: "{{ crowdsec_appsec_collections }}"
  register: crowdsec_appsec_collection_install
  changed_when: "'already installed' not in crowdsec_appsec_collection_install.stdout"
  failed_when:
    - crowdsec_appsec_collection_install.rc != 0
    - "'already installed' not in crowdsec_appsec_collection_install.stdout"
    - "'can\\'t find' not in crowdsec_appsec_collection_install.stderr"

- name: Install AppSec-specific parsers
  ansible.builtin.command:
    cmd: "{{ _cscli_binary }} parsers install {{ item }}"
  loop:
    - crowdsecurity/appsec-default
  register: crowdsec_appsec_parser_install
  changed_when: "'already installed' not in crowdsec_appsec_parser_install.stdout"
  failed_when:
    - crowdsec_appsec_parser_install.rc != 0
    - "'already installed' not in crowdsec_appsec_parser_install.stdout"
    - "'can\\'t find' not in crowdsec_appsec_parser_install.stderr"

- name: Enable AppSec in profiles
  ansible.builtin.blockinfile:
    path: "{{ _crowdsec_profiles_file }}"
    marker: "# {mark} ANSIBLE MANAGED - APPSEC PROFILE"
    block: |
      name: appsec_profile
      filters:
        - Alert.Remediation == true && Alert.GetScope() == "Ip"
      decisions:
        - type: ban
          duration: 4h
      on_success: break
    create: true
    mode: '0644'
  notify:
    - Restart crowdsec

- name: Display AppSec configuration
  ansible.builtin.debug:
    msg: "AppSec enabled with collections: {{ crowdsec_appsec_collections }}"
