---
- name: Converge
  hosts: all
  become: true
  gather_facts: true

  pre_tasks:
    - name: Update apt cache (Debian)
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      when: ansible_os_family == "Debian"
      changed_when: false

    - name: Install system dependencies (Debian)
      ansible.builtin.apt:
        name:
          - curl
          - ca-certificates
          - iptables
          - systemd
        state: present
      when: ansible_os_family == "Debian"

    - name: Install system dependencies (RHEL)
      ansible.builtin.dnf:
        name:
          - curl
          - ca-certificates
          - iptables
          - systemd
        state: present
      when: ansible_os_family == "RedHat"

  roles:
    - role: k3s
      vars:
        k3s_mode: server
        k3s_cni: flannel  # Use flannel for testing (faster than Calico)
        k3s_version: v1.28.5+k3s1
        k3s_wait_for_ready: true
        k3s_configure_kubectl: true
        k3s_configure_firewall: false
        k3s_disable_components:
          - traefik
          - servicelb
