---
# System Maintenance Runbook
- name: "System Maintenance"
  hosts: all
  become: true
  gather_facts: true

  vars_files:
    - "../../../group_vars/all/main.yml"
    - "../../../group_vars/{{ ansible_os_family | lower }}/main.yml"

  tasks:
    - name: "Update package cache"
      ansible.builtin.package:
        update_cache: true

    - name: "Upgrade all packages (Debian/Ubuntu)"
      ansible.builtin.apt:
        upgrade: dist
        autoremove: true
        autoclean: true
        state: latest # noqa package-latest
      when: ansible_os_family == "Debian"

    - name: "Update all packages (RedHat/CentOS)"
      ansible.builtin.dnf:
        name: "*"
        state: latest # noqa package-latest
        update_cache: true
        best: true
      when: ansible_os_family == "RedHat"

    - name: "Install Common packages"
      ansible.builtin.package:
        name: "{{ common_packages }}"
        state: present

    - name: "Install OS-specific packages"
      ansible.builtin.package:
        name: "{{ os_specific_packages }}"
        state: present

    - name: "Check disk space"
      ansible.builtin.command: df -h
      register: disk_usage
      changed_when: false

    - name: "Display disk usage"
      ansible.builtin.debug:
        msg: "{{ disk_usage.stdout_lines }}"
