---
# Quick Variable Test
- name: "Test Variable Loading"
  hosts: all
  gather_facts: true
  
  tasks:
    - name: "Show current working directory"
      ansible.builtin.debug:
        msg: "Playbook dir: {{ playbook_dir }}"
        
    - name: "Test common_packages variable"
      ansible.builtin.debug:
        msg: "common_packages is {{ 'DEFINED' if common_packages is defined else 'UNDEFINED' }}"
        
    - name: "Show common_packages content"
      ansible.builtin.debug:
        var: common_packages
      when: common_packages is defined
        
    - name: "Test os_specific_packages variable"
      ansible.builtin.debug:
        msg: "os_specific_packages is {{ 'DEFINED' if os_specific_packages is defined else 'UNDEFINED' }}"
        
    - name: "Show os_specific_packages content"
      ansible.builtin.debug:
        var: os_specific_packages
      when: os_specific_packages is defined
        
    - name: "Show host groups"
      ansible.builtin.debug:
        msg: "This host belongs to groups: {{ group_names }}"
        
    - name: "Show OS family"
      ansible.builtin.debug:
        msg: "OS Family: {{ ansible_os_family }} | Distribution: {{ ansible_distribution }}"
