---
# Playbook to configure NFS servers and clients
#
# Usage examples:
#
# Configure NFS servers:
#   ansible-playbook -i inventories/production.yml playbooks/storage/nfs.yml --tags nfs-server
#
# Configure NFS clients:
#   ansible-playbook -i inventories/production.yml playbooks/storage/nfs.yml --tags nfs-client
#
# Configure both:
#   ansible-playbook -i inventories/production.yml playbooks/storage/nfs.yml

- name: Configure NFS servers
  hosts: nfs_servers
  become: true
  tags:
    - nfs
    - nfs-server
    - storage

  vars:
    nfs_mode: server

  tasks:
    - name: Include NFS role for servers
      ansible.builtin.include_role:
        name: nfs

- name: Configure NFS clients
  hosts: nfs_clients
  become: true
  tags:
    - nfs
    - nfs-client
    - storage

  vars:
    nfs_mode: client

  tasks:
    - name: Include NFS role for clients
      ansible.builtin.include_role:
        name: nfs
