---
# Playbook to configure NFS servers and clients (Using Community Role)
# Uses geerlingguy.nfs
#
# Usage examples:
#   ansible-playbook -i inventories/production.yml playbooks/storage/nfs.yml --tags nfs-server
#   ansible-playbook -i inventories/production.yml playbooks/storage/nfs.yml --tags nfs-client

- name: Configure NFS servers and clients
  hosts: nfs_servers,nfs_clients
  become: true
  gather_facts: true
  tags:
    - nfs
    - storage

  pre_tasks:
    - name: Set NFS exports for servers
      ansible.builtin.set_fact:
        nfs_exports: "{{ nfs_exports | default([]) }}"
      when: inventory_hostname in groups['nfs_servers']

  roles:
    - role: geerlingguy.nfs
