---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ubuntu-tailscale
    image: geerlingguy/docker-ubuntu2204-ansible:latest
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
  - name: debian-tailscale
    image: geerlingguy/docker-debian12-ansible:latest
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  playbooks:
    converge: converge.yml
  inventory:
    host_vars:
      ubuntu-tailscale:
        ansible_python_interpreter: /usr/bin/python3
      debian-tailscale:
        ansible_python_interpreter: /usr/bin/python3
verifier:
  name: ansible
