---
# Debian-specific variables for k3s

# Required system packages
k3s_system_packages: "{{ k3s_required_packages_debian }}"

# Firewall package
k3s_firewall_package: ufw

# Service manager
k3s_service_manager: systemd
