---
# Debian/Ubuntu Tailscale repository setup
- name: Create keyrings directory (Debian/Ubuntu)
  ansible.builtin.file:
    path: /usr/share/keyrings
    state: directory
    mode: '0755'
    owner: root
    group: root
  tags: [tailscale, debian, repository]

- name: Download and add Tailscale GPG key (Debian/Ubuntu)
  ansible.builtin.get_url:
    url: "{{ tailscale_repo_key_url }}"
    dest: "{{ tailscale_repo_keyring }}"
    mode: '0644'
    owner: root
    group: root
    timeout: 30
  tags: [tailscale, debian, repository]

- name: Download and add Tailscale repository list (Debian/Ubuntu)
  ansible.builtin.get_url:
    url: "{{ tailscale_repo_list_url }}"
    dest: "{{ tailscale_repo_list_file }}"
    mode: '0644'
    owner: root
    group: root
    timeout: 30
  notify: Restart tailscaled
  tags: [tailscale, debian, repository]

- name: Update package cache (Debian/Ubuntu)
  ansible.builtin.apt:
    update_cache: true
  tags: [tailscale, debian, repository]
