---
# Debian/Ubuntu specific Docker installation tasks
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  tags: [docker, install]

- name: Install required packages for Docker repository
  ansible.builtin.package:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - apt-transport-https
    state: present
  tags: [docker, install]

- name: Install software-properties-common (Ubuntu)
  ansible.builtin.package:
    name: software-properties-common
    state: present
  when: ansible_distribution == "Ubuntu"
  tags: [docker, install]

- name: Create keyring directory
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    owner: root
    group: root
    mode: "0755"
  tags: [docker, install]

- name: Add Docker GPG key
  ansible.builtin.get_url:
    url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'
    force: true
  tags: [docker, install]

- name: Build Docker repository string
  ansible.builtin.set_fact:
    docker_repo_string: "https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
  tags: [docker, install]

- name: Add Docker repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] {{ docker_repo_string }}"
    state: present
    filename: docker
  tags: [docker, install]

- name: Update apt cache after adding repository
  ansible.builtin.apt:
    update_cache: true
  tags: [docker, install]
