---
# Main Site Playbook
- name: "Apply common configuration to all hosts"
  hosts: all
  become: true
  gather_facts: true
  
  tasks:
    - name: "Install common packages"
      package:
        name: "{{ common_packages }}"
        state: present
        
    - name: "Configure timezone"
      timezone:
        name: "{{ timezone }}"
        
    - name: "Ensure SSH is configured securely"
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        backup: true
      loop:
        - { regexp: '^PasswordAuthentication', line: 'PasswordAuthentication no' }
        - { regexp: '^PermitRootLogin', line: 'PermitRootLogin no' }
        - { regexp: '^Port', line: 'Port {{ ssh_port }}' }
      notify: restart_ssh
      
  handlers:
    - name: restart_ssh
      service:
        name: "{{ ssh_service_name | default('ssh') }}"
        state: restarted
