---
- name: Converge
  hosts: all
  become: true
  gather_facts: true

  pre_tasks:
    - name: Update apt cache (Debian)
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      when: ansible_os_family == "Debian"
      changed_when: false

    - name: Install Docker dependencies (Debian)
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - python3-pip
        state: present
      when: ansible_os_family == "Debian"

    - name: Install Docker dependencies (RHEL)
      ansible.builtin.dnf:
        name:
          - yum-utils
          - python3-pip
        state: present
      when: ansible_os_family == "RedHat"

    - name: Install Docker Python module
      ansible.builtin.pip:
        name:
          - docker
          - requests
        state: present

    - name: Add Docker GPG key (Debian)
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
        state: present
      when: ansible_os_family == "Debian"

    - name: Add Docker repository (Debian)
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
        state: present
      when: ansible_os_family == "Debian"

    - name: Add Docker repository (RHEL)
      ansible.builtin.yum_repository:
        name: docker-ce
        description: Docker CE Repository
        baseurl: https://download.docker.com/linux/centos/$releasever/$basearch/stable
        gpgcheck: true
        gpgkey: https://download.docker.com/linux/centos/gpg
        enabled: true
      when: ansible_os_family == "RedHat"

    - name: Install Docker (Debian)
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
        update_cache: true
      when: ansible_os_family == "Debian"

    - name: Install Docker (RHEL)
      ansible.builtin.dnf:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
      when: ansible_os_family == "RedHat"

    - name: Start Docker service
      ansible.builtin.systemd:
        name: docker
        state: started
        enabled: true

  roles:
    - role: cadvisor
      vars:
        cadvisor_install_method: docker
        cadvisor_bind_address: "0.0.0.0"
