---
galaxy_info:
  role_name: nfs
  author: Sidney
  description: Install and configure NFS server and client on Debian/Ubuntu and RedHat/Rocky Linux
  company: Home Lab
  license: MIT
  min_ansible_version: '2.12'

  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
        - noble
    - name: Debian
      versions:
        - bullseye
        - bookworm
    - name: EL
      versions:
        - all

  galaxy_tags:
    - nfs
    - storage
    - filesystem
    - network
    - server
    - client
    - share
    - mount

dependencies: []
