---
# k3s role default variables

# k3s installation mode: 'server', 'agent', or 'combined' (server + agent)
k3s_mode: combined

# k3s version to install (leave empty for latest stable)
k3s_version: v1.28.5+k3s1

# k3s server configuration
k3s_server_enabled: true
k3s_server_host: "{{ ansible_default_ipv4.address }}"
k3s_server_port: 6443

# k3s agent configuration
k3s_agent_enabled: false

# Server token for agent nodes to join (must be set for agent nodes)
k3s_server_token: ""
k3s_server_url: ""

# CNI selection: 'calico' or 'flannel' (k3s default)
k3s_cni: calico

# Calico version
calico_version: v3.27.0

# Calico configuration
calico_ipv4_pool_cidr: 10.42.0.0/16
calico_ipv4_pool_block_size: 26
calico_encapsulation: VXLAN  # Options: VXLAN, IPIP, IPIPCrossSubnet, VXLANCrossSubnet, None

# Cluster CIDR (must match Calico pool)
k3s_cluster_cidr: 10.42.0.0/16
k3s_service_cidr: 10.43.0.0/16

# k3s installation options
k3s_install_dir: /usr/local/bin
k3s_config_dir: /etc/rancher/k3s
k3s_data_dir: /var/lib/rancher/k3s

# Disable default k3s components
k3s_disable_components:
  - traefik
  - servicelb

# Additional k3s server arguments
k3s_server_extra_args: []

# Additional k3s agent arguments
k3s_agent_extra_args: []

# Firewall configuration
k3s_configure_firewall: false
k3s_firewall_zone: public

# Firewall ports for k3s server
k3s_server_firewall_ports:
  - 6443/tcp   # Kubernetes API
  - 10250/tcp  # Kubelet
  - 2379/tcp   # etcd client
  - 2380/tcp   # etcd peer

# Firewall ports for k3s agent
k3s_agent_firewall_ports:
  - 10250/tcp  # Kubelet

# Calico firewall ports
calico_firewall_ports:
  - 179/tcp    # BGP
  - 4789/udp   # VXLAN

# kubectl configuration
k3s_configure_kubectl: true
k3s_kubeconfig_path: /etc/rancher/k3s/k3s.yaml
k3s_kubeconfig_user_path: "{{ ansible_env.HOME }}/.kube/config"

# Service configuration
k3s_service_enabled: true
k3s_service_state: started

# System requirements
k3s_required_packages_debian:
  - curl
  - ca-certificates
  - iptables

k3s_required_packages_redhat:
  - curl
  - ca-certificates
  - iptables

# Uninstall script location
k3s_uninstall_script_server: /usr/local/bin/k3s-uninstall.sh
k3s_uninstall_script_agent: /usr/local/bin/k3s-agent-uninstall.sh

# Wait for k3s to be ready
k3s_wait_for_ready: true
k3s_ready_timeout: 300

# Token file location
k3s_token_file: /var/lib/rancher/k3s/server/node-token
