---
# Package update tasks
- name: Update package cache
  ansible.builtin.package:
    update_cache: true
  tags: [maintenance, updates]

- name: Upgrade all packages (Debian/Ubuntu)
  ansible.builtin.apt:
    upgrade: dist
    autoremove: true
    autoclean: true
    state: latest # noqa package-latest
  when: ansible_os_family == "Debian"
  tags: [maintenance, updates]

- name: Update all packages (RedHat/CentOS)
  ansible.builtin.dnf:
    name: "*"
    state: latest # noqa package-latest
    update_cache: true
    best: true
  when: ansible_os_family == "RedHat"
  tags: [maintenance, updates]
