---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: wazuh-allinone-debian
    image: geerlingguy/docker-debian12-ansible:latest
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    groups:
      - wazuh_servers

  - name: wazuh-agent-debian
    image: geerlingguy/docker-debian12-ansible:latest
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    groups:
      - wazuh_agents

  - name: wazuh-allinone-rhel
    image: geerlingguy/docker-rockylinux9-ansible:latest
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    groups:
      - wazuh_servers

provisioner:
  name: ansible
  config_options:
    defaults:
      callbacks_enabled: profile_tasks,timer,yaml
      stdout_callback: yaml
  inventory:
    group_vars:
      all:
        wazuh_version: "4.9.0"
        wazuh_disable_updates: true
      wazuh_servers:
        wazuh_install_mode: all-in-one
        wazuh_dashboard_password: "TestPassword123!"
        wazuh_manager_email_notification: true
        wazuh_manager_email_to: "test@example.com"
        wazuh_manager_vulnerability_detection: true
        wazuh_manager_active_response: true
        wazuh_monitor_docker: true
        wazuh_trivy_integration: true
        wazuh_indexer_cluster_type: single-node
      wazuh_agents:
        wazuh_install_mode: agent
        wazuh_agent_manager_ip: "172.17.0.2"
        wazuh_agent_auth_method: password
        wazuh_agent_auth_password: "agent-test-password"
        wazuh_monitor_docker: true
        wazuh_trivy_integration: true

verifier:
  name: ansible
