---
# handlers file for nfs

- name: Restart nfs server
  ansible.builtin.service:
    name: "{{ nfs_server_service }}"
    state: restarted
  when: nfs_mode in ['server', 'both']

- name: Reload nfs server
  ansible.builtin.service:
    name: "{{ nfs_server_service }}"
    state: reloaded
  when: nfs_mode in ['server', 'both']

- name: Restart nfs idmapd
  ansible.builtin.service:
    name: "{{ nfs_idmapd_service }}"
    state: restarted

- name: Restart rpcbind
  ansible.builtin.service:
    name: "{{ nfs_rpcbind_service }}"
    state: restarted
  when: ansible_os_family == 'RedHat'

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Export nfs shares
  ansible.builtin.command: exportfs -ra
  changed_when: false
  when: nfs_mode in ['server', 'both']
